import React from "react";
import LogoS from "./LogoS.svg";
import "./Header.css";
import PopUp from "../PopUp/PopUp";

const Header = () => {
  const RestartContent = () => {
    return (
      <div class="confirmation-dialog">
        <p>
          You will quit the current game and <br />
          <span class="not-saved">this game will not be saved</span>.
        </p>
        <p class="confirm-question">Are you sure about to restart?</p>
        <button
          class="button-1st"
          onClick={() => {
            window.location.href = "/";
          }}
        >
          Restart
        </button>
      </div>
    );
  };
  const AboutContent = () => {
    return (
      <div class="about-content">
        <div class="about-column">
          <ul class="about-text">
            <li>
              Dedicated to all Avalon players, this website is created with 80%
              of its code generated by ChatGPT.
            </li>
            <li>
              I am very grateful to ChatGPT, which has given me, an ordinary
              designer, the ability to code from scratch. Technology is really
              amazing~ As a practice project, I am quite satisfied with the
              results!
            </li>
            <li>
              The reason why the functions were relatively simple is because I
              had to write the code myself...{" "}
              <span style={{ textDecorationLine: "line-through" }}>
                Otherwise, I would definitely have to deal with some fancy
                things that would eat my Engineers’ brains.
              </span>
            </li>
            <li>
              It’s now on its 5th version... I had some ideas before about
              adding a feature to assist in calculating the probability of who
              is the evil role, but it was too difficult to implement and the
              situation was too complex, so I kept simplifying it to the current
              version. If any 1 has a good method to calculate probabilities,
              please contact me as soon as possible~
            </li>
            <li>
              Thanks to all participants who helped test the game and fix bugs!
            </li>
            <li>
              Located in Sunnyvale, CA, 94086, I hope everyone can invite me to
              a game night! Feel free to visit my Instagram or website and leave
              any feedback anytime! My email： yi.liu.o0ez0o@gmail.com
            </li>
          </ul>
        </div>
        <div class="about-column">
          <ul class="about-text">
            <li>
              谨以此网站献给所有喜欢玩阿瓦隆的玩家，
              此网站的CODE80%均用chatGPT生成。
            </li>
            <li>
              还是很感激ChatGPT的，让我这个平平无奇设计师都有了code from
              scratch的能力。科技还真是了不起呢~作为练习的project，结果上觉得还是很满意哒！
            </li>
            <li>
              这次做的功能比较简单那是因为要自己写code...
              <span style={{ textDecorationLine: "line-through" }}>
                不然肯定是要搞些花里胡哨的东西折磨我的eng...
              </span>
            </li>
            <li>
              光是设计都迭代了5个版本呢hhhh~之前有想一些辅助计算谁是坏人的概率的功能，但是都太难实现了，情况过于复杂，所以就一再简化成现在这个版本了。如果有小伙伴已经有怎么才能计算概率的好方法~请快点和我联系~
            </li>
            <li>感谢所有参与测试，帮我修bug的小伙伴们！</li>
            <li>
              坐标Sunnyvale, CA,
              94086，希望大家有桌游局喊我！欢迎随时去我的ins或者我的网站玩耍和留言！我的邮箱：yi.liu.o0ez0o@gmail.com
            </li>
          </ul>
          <p class="about-text" style={{ textAlign: "right", width: "fill" }}>
            by 机智勇敢的一线曙光 2023.03.24
          </p>
        </div>
      </div>
    );
  };
  return (
    <div className="header-container">
      <div className="header-left">
        <img src={LogoS} alt="LogoS" className="header-logo" />
        <div className="header-text">Avalon Note Ast.</div>
      </div>
      <div className="header-right">
        <div className="header-link">Export Game</div>
        <PopUp title="About" titleClass={"header-link"} inCardTitle={"About"}>
          {AboutContent()}
        </PopUp>
        <PopUp
          title="! Restart"
          titleClass={"header-link red"}
          inCardTitle={"Restart Game"}
        >
          {RestartContent()}
        </PopUp>
      </div>
    </div>
  );
};

export default Header;
